# Generated by Django 5.2.14 on 2026-06-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_title',
            field=models.CharField(default='Untitled', max_length=50),
        ),
    ]
