# Generated by Django 5.2.14 on 2026-06-28 11:09

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(default='course/category/default.svg', upload_to='course/category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='overview',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
