# Generated by Django 5.2.14 on 2026-07-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_category_image_alter_course_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
