# Generated by Django 5.2.14 on 2026-07-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='score',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
