# Generated by Django 5.2.14 on 2026-06-26 10:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_score_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('user', 'course')},
        ),
        migrations.RemoveField(
            model_name='score',
            name='email',
        ),
        migrations.RemoveField(
            model_name='score',
            name='name',
        ),
    ]
