# Generated by Django 5.2.14 on 2026-06-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_discount_percent_course_is_free_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='skill_level',
            field=models.CharField(choices=[('مقدماتی', 'مقدماتی'), ('متوسط', 'متوسط'), ('حرفه ای', 'حرفه ای')], max_length=20, null=True),
        ),
    ]
