# Generated by Django 5.2.14 on 2026-06-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_score_unique_together_remove_score_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='skill_level',
            field=models.CharField(choices=[('مقدماتی', 'مقدماتی'), ('متوسط', 'متوسط'), ('حرفه\u200cای', 'حرفه\u200cای')], max_length=20),
        ),
    ]
