# Generated by Django 5.2.14 on 2026-06-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_commentlike_comment_alter_commentlike_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
