# Generated by Django 5.2.14 on 2026-06-27 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_score_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='value',
        ),
    ]
