# Generated by Django 5.2.14 on 2026-06-22 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score', to='course.course'),
        ),
    ]
