# Generated by Django 5.2.14 on 2026-06-22 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_score_course'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('email', 'course')},
        ),
    ]
