# Generated by Django 5.2.14 on 2026-06-27 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_score_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='course.course'),
        ),
    ]
