# Generated by Django 5.2.14 on 2026-06-22 16:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_score_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='course.score')),
            ],
        ),
    ]
