# Generated by Django 5.2.14 on 2026-06-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_score_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='certification',
            field=models.CharField(choices=[('بله', 'بله'), ('نه', 'نه')], max_length=20, null=True),
        ),
    ]
