# Generated by Django 5.2.14 on 2026-06-27 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_alter_course_certification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='degree',
        ),
    ]
