# Generated by Django 5.2.14 on 2026-06-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_remove_comment_parent_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discount_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
