# Generated by Django 5.2.14 on 2026-06-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_course_discount_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='course/category/default.jpg', upload_to='course/'),
        ),
    ]
