# Generated by Django 5.2.14 on 2026-06-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(default='course/category/default.svg', upload_to='course/'),
        ),
    ]
