# Generated by Django 5.2.14 on 2026-06-24 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_alter_lesson_video_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
