# Generated by Django 5.2.14 on 2026-06-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='counted_views',
            field=models.IntegerField(default=0),
        ),
    ]
