# Generated by Django 5.2.14 on 2026-06-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0026_alter_course_skill_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='skill_level',
            field=models.CharField(choices=[('beginner', 'مقدماتی'), ('intermediate', 'متوسط'), ('advanced', 'حرفه\u200cای')], max_length=20, null=True),
        ),
    ]
