# Generated by Django 5.2.14 on 2026-06-24 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_question_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['created_date']},
        ),
        migrations.AddField(
            model_name='answer',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='website.answer'),
        ),
    ]
