# Generated by Django 5.2.14 on 2026-07-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_questionlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentoruser',
            name='expertise',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
    ]
