# Generated by Django 5.2.14 on 2026-06-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_answer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('business', 'کسب\u200cوکار'), ('development', 'توسعه'), ('design', 'طراحی'), ('marketing', 'بازاریابی'), ('courses', 'دوره\u200cها'), ('start', 'شروع'), ('profile', 'حساب کاربری و پروفایل')], max_length=20, null=True),
        ),
    ]
