# Generated by Django 5.2.14 on 2026-06-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_question_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=25)),
                ('confirm_password', models.CharField(max_length=25)),
                ('avatar', models.ImageField(default='mentor/default.jpg', upload_to='mentor/')),
                ('expertise', models.CharField(max_length=50)),
            ],
        ),
    ]
