# Generated by Django 5.2.14 on 2026-06-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_mentoruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentoruser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
