# Generated by Django 5.2.14 on 2026-06-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='short_description',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
