# Generated by Django 5.2.14 on 2026-06-28 11:09

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_alter_instructor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
