# Generated by Django 5.2.14 on 2026-06-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_instructor_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='short_description',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
