# Generated by Django 5.2.14 on 2026-06-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_alter_instructor_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
