# Generated by Django 5.2.14 on 2026-07-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_alter_instructor_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='university',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='expertise',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
