# Generated by Django 5.2.14 on 2026-06-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0004_instructor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
