# Generated by Django 5.2.14 on 2026-06-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0007_alter_instructor_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='counted_views',
            field=models.IntegerField(default=0),
        ),
    ]
