# Generated by Django 5.2.14 on 2026-06-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('primary', 'آبی'), ('success', 'سبز'), ('danger', 'قرمز'), ('warning', 'زرد'), ('info', 'فیروزه\u200cای'), ('secondary', 'خاکستری'), ('orange', 'نارنجی'), ('purple', 'بنفش')], default='primary'),
        ),
    ]
