# Generated by Django 5.2.14 on 2026-06-23 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='info',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(null=True, upload_to='blog/video', validators=[django.core.validators.FileExtensionValidator(['mp4'])]),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/image/default.jpg', upload_to='blog/image'),
        ),
    ]
