# Generated by Django 5.2.14 on 2026-06-23 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_replaycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='replaycomment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replaycomment', to='blog.post'),
        ),
    ]
