# Generated by Django 5.2.14 on 2026-06-23 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_replaycomment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replaycomment',
            name='post',
        ),
    ]
