# Generated by Django 5.2.14 on 2026-06-23 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_replaycomment_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='replaycomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='replaycomment',
            name='question_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_replies', to='blog.comment'),
        ),
    ]
