# Generated by Django 5.2.14 on 2026-06-23 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_replaycomment_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replaycomment',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='replaycomment',
            name='question_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replaycomment', to='blog.comment'),
        ),
    ]
