# Generated by Django 5.2.14 on 2026-06-24 18:53

import blog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_replaycomment_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/image/default.jpg', upload_to=blog.models.post_media_upload_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(null=True, upload_to=blog.models.post_media_upload_path, validators=[django.core.validators.FileExtensionValidator(['mp4'])]),
        ),
    ]
